name: Build Targets
on: [push]
jobs:
  Build-Action:
    runs-on: ubuntu-latest
    steps:
      - run: Rscript ${{github.workspace}}/setup_packages.R
      - run: Rscript -e "library(targets); tar_make()"